services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  bot:
    build: .
    container_name: telegram_bot
    command: python main.py
    depends_on:
      - redis
      - mongo
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=redis://redis:6379/3
      - MONGO_URL=mongodb://mongo:27017/KleineAnzeigen
    restart: always

  celery:
    build: .
    container_name: celery_worker
    command: celery -A core.celery_client worker --loglevel=info
    depends_on:
      - redis
      - mongo
    environment:
      - REDIS_URL=redis://redis:6379/3
      - MONGO_URL=mongodb://mongo:27017/KleineAnzeigen
      - BOT_TOKEN=${BOT_TOKEN}

    restart: always

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A core.celery_client beat --loglevel=info
    depends_on:
      - redis
      - mongo
      - celery
    environment:
      - REDIS_URL=redis://redis:6379/3
      - MONGO_URL=mongodb://mongo:27017/KleineAnzeigen
      - BOT_TOKEN=${BOT_TOKEN}  
    restart: always

volumes:
  mongo_data:
